### ISSUE TITLE
[BUG] Collapsing a drawer closes all drawers

### ISSUE THREAD

**Issue by timlinux** [unicef-drp/GeoSight-OS#42]
## Problem

Currently when in the project view, if I close a drawer of layers, all the other drawers close too:

![Peek 2023-08-25 09-33](https://github.com/unicef-drp/GeoSight-OS/assets/178003/bbcfb9c1-25f0-4013-82ad-c3608a7a908b)

## Propose Solution

Modify the behaviour such that clicking on a drawer hides only the items in that drawer and any visible items in other drawers remain visible.

## Environment

Browser: Firefox  
![image](https://github.com/unicef-drp/GeoSight-OS/assets/178003/b7a6846c-70aa-4764-a2a2-f496a9e2eb28)

OS: Linux

Geosight-OS Version:  Version 1.5.0

**Comment by janbur** [comment]
This has been fixed.
