### ISSUE TITLE
[Feature] Make admin button contextually aware

### ISSUE THREAD

**Issue by timlinux** [unicef-drp/GeoSight-OS#46]
# Problem

When viewing a project, it is common to want to edit the project if you have the needed permissions. Right now, when you click on the admin button here:

![image](https://github.com/unicef-drp/GeoSight-OS/assets/178003/58a48d47-4d35-4295-96a4-74057bb97044)

It takes you to the project list admin view.

# Proposed Solution

If you are on the landing page we could continue the current behaviour.
If you are in a project view, the admin page could take you to the admin area for the associated project.

**Comment by janbur** [comment]
This is implemented:
![image](https://github.com/unicef-drp/GeoSight-OS/assets/37516253/5c741135-fcf4-4fac-a225-e844dd161896)
